// Generates src/environments/environment.ts from `.env` (or from process env vars, e.g. in CI).
// Angular has no native .env support, so this runs before start/build/test (see package.json).
// Without credentials it still generates the file with empty values: the app falls back to demo auth.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envFile = resolve(root, '.env');
const target = resolve(root, 'src/environments/environment.ts');

if (existsSync(envFile)) process.loadEnvFile(envFile);

const supabaseUrl = (process.env.SUPABASE_URL ?? '').trim();
const supabaseAnonKey = (
  process.env.SUPABASE_PUBLISHABLE_KEY ??
  process.env.SUPABASE_ANON_KEY ??
  ''
).trim();

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[set-env] SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY missing: the app will run with demo auth. ' +
      'Copy .env.example to .env and fill them in.',
  );
}

const contents = `// AUTO-GENERATED by scripts/set-env.mjs from .env — do not edit or commit.
import type { Environment } from './environment.model';

export const environment: Environment = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
};
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, contents);
console.log(`[set-env] wrote ${target}`);
